### ISSUE TITLE
Improve support for 32 bit systems

### ISSUE THREAD

**Issue by nhz2** [reallyasi9/TruncatedStreams.jl#1]
I think these should be `Int64` to support reading large files on 32 bit systems.
https://github.com/reallyasi9/TruncatedStreams.jl/blob/45158b0b36f666aa57ebbf0b8a9f331917a10634/src/fixedlengthio.jl#L81-L83

**Comment by reallyasi9** [comment]
I added a test with a stream longer than 1<<32 and the old code passed it, but I couldn't figure out exactly why. Updated to use Int64 just in case.

**Comment by nhz2** [comment]
I think the issue is on 32-bit Julia 1<<32 is zero because regular int literals are 32-bit:
```sh
$ julia +1.10~x86 -e 'println(1<<32)'
0
```
 This should work:
```sh
$ julia +1.10~x86 -e 'println(Int64(1)<<32)'
4294967296
```
