### ISSUE TITLE
Improve support for skipping

### ISSUE THREAD

**Issue by nhz2** [reallyasi9/TruncatedStreams.jl#2]
There are some IO types, for example from `CodecZlib.jl`, that support `skip`, but don't support `seek`, 
so it would be good to `skip` instead of `seek` the underlying IO here.
https://github.com/reallyasi9/TruncatedStreams.jl/blob/45158b0b36f666aa57ebbf0b8a9f331917a10634/src/fixedlengthio.jl#L115-L119

**Comment by reallyasi9** [comment]
I worried about this. I've implemented skip-only and seek-only methods for FixedLengthIO, and faked it in SentinelIO (which sometimes requires `position(io)` and `read(io, UInt8)` to be called) in https://github.com/reallyasi9/TruncatedStreams.jl/commit/f9657177a4ddada5142016a6d739108f63ad7a91
